---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

df <- read_excel(r"(H:\Downloads\Disinformation Data.xlsx)")

names(df)


df <- df.o 

df <- df %>% select(year,journal_name,article_title,authors,citations)

"year"                 "journal_name"         "article_title"       
[4] "authors"              "citations"            "article_id"          
[7] "link"

library(extracat)
```

```{r fig.height=6, fig.width=7, paged.print=TRUE}

#df <- data.frame(replicate(25,sample(0:1,1000,rep=TRUE)))
df2 <- as.data.frame(lapply(df, function(cc) cc[ sample(c(TRUE, NA), prob = c(0.85, 0.15), size = length(cc), replace = TRUE) ]))
# visualise the number of missings in cases using visna from extracat
extracat::visna(df)

names(df2)
```

```{r}
# what if we explore the value of air temperature and humidity based on
# the missingness of each
  df %>%
    bind_shadow() %>%
    ggplot(aes(x = citations,
               fill = article_title)) +
        geom_histogram()
```

```{r}
library(extracat)
visna(GeneEx)
visna(GeneEx, sort = b, sort.method=optile)


names(df)


library(visdat)
vis_dat(df)


df2 %>%
    bind_shadow() %>%
    ggplot(aes(x = year,
               fill = citations)) +
        geom_histogram()
```

```{r}
??geom_miss_point
library(naniar)

ggplot(
  data = df,
  mapping = aes(x = journal_name, y = citations)) +     
  geom_miss_point()


ggplot(data = df,          # data frame with shadow columns
  mapping = aes(x = citations, # numeric or date column
                colour = journal_name)) + # shadow column of interest
  geom_density()                          # plots the density curves
```

```{r}

sum(is.na(df))/(sum(is.na(df))+sum(!is.na(df)))

sum(!is.na(df))/(sum(is.na(df))+sum(!is.na(df)))



gg_miss_upset(df, 
              nsets = 20,
              nintersects = 510)


ggplot(df,
       aes(x = sum(!is.na(article_title)),
           colour = sum(is.na(citations)))) + 
  geom_miss_point()




ggplot(
  data = df,
  mapping = aes(x = !is.na(article_title), y = sum(is.na(citations))))+
  geom_miss_point()
names(df)
```
